platform :ios, '14.0'
use_frameworks!

target 'RollbarCocoapodsSwift' do
  #pod 'RollbarCommon', '~> 3.0.1'
  #pod 'RollbarCrashReport', '~> 3.0.1'
  pod 'RollbarNotifier', '~> 3.0.1'
  #pod 'RollbarAUL', :path => '/Users/matux/code/Rollbar/rollbar-apple'
  #pod 'RollbarCocoaLumberjack', :path => '/Users/matux/code/Rollbar/rollbar-apple'
  #pod 'RollbarDeploys', :path => '/Users/matux/code/Rollbar/rollbar-apple'
end

